### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by sinchb** [suvit/suds-passworddigest#1]
Thinks a lot for your project. I use your code in my [onvif](https//github.com/quatanium/onvif) project. I think it's a good idea to import UsernameDigestToken in **init**.py

``` python
from token import UsernameDigestToken
__all__ = ('UsernameDigestToken', 'VERSION')
```

so we can import UsernameDigestToken like this:

``` python
from suds_passworddigest import UsernameDigestToken
```

I have forked your project and have it fixed. Hope helpful.

https://github.com/sinchb/suds-passworddigest

**Comment by risfutile** [comment]
maybe mention on the onvif project page to install THIS forked version?
ofc it won't work otherwise. and finding this page is pure luck...

**Comment by sinchb** [comment]
@risfutile 
sorry... [onvif](https://pypi.python.org/pypi/onvif/0.1.2) has been updated. And I install TIS version:

```
from suds_passworddigest.token import UsernameDigestToken
```

:)
