### ISSUE TITLE
compatibility with Ubuntu suds package

### ISSUE THREAD

**Issue by grischa** [suvit/suds-passworddigest#3]
The Ubuntu python-suds package includes some improvements to timezone handling that are incompatible with the use in here.
Please include code like this:

``` python
try:
    from suds.sax.date import UtcTimezone as UTC
except ImportError:
    from suds.sax.date import UTC
```

in `token.py`

**Comment by eLvErDe** [comment]
Hello,

This is definitely not a proper fix. Check my PR which is working perfectly fine:
https://github.com/suvit/suds-passworddigest/pull/4

Regards, Adam.

**Comment by grischa** [comment]
Yeah, I agree it wasn't a proper fix. Thanks for fixing it!
